font_family Hack
font_size   14
modify_font cell_width  95%

macos_option_as_alt                 yes
macos_quit_when_last_window_closed  yes
macos_show_window_title_in          window
macos_dock_badge_on_bell            no
hide_window_decorations             titlebar-only

cursor #B5B4B4
cursor_blink_interval 0

enable_audio_bell   no
clear_all_shortcuts yes

window_margin_width   5
bell_on_tab           no
enable_audio_bell     no
allow_remote_control  yes
listen_on             unix:/tmp/kitty


background #171721
foreground #d0d0d0

color0  #1b1918
color1  #DC322F
color2  #299C00
color3  #d5911a
color4  #407ee7
color5  #6666ea
color6  #00ad9c
color7  #D3D7CF

color8  #766e6b
color9  #CD0000
color10 #299C00
color11 #d5911a
color12 #407ee7
color13 #6666ea
color14 #00ad9c
color15 #f1efee

map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard

remember_window_size  no
initial_window_width  1500
initial_window_height 1000
