exec {
  hypridle
  aa-notify -p -s 1 -w 60 -f /var/log/audit/audit.log
  # easyeffects --service-mode --hide-window

  Telegram
  thunderbird
  dex ~/.local/share/applications/MAX.desktop
  ~/bin/wlsunset.sh start
}

assign [app_id="org.telegram.desktop"] 3
assign [app_id="chrome-*" title="MAX"] 3
assign [app_id="chrome-*" title="MAX"] floating disable

exec {
  sleep 5 && \
    swaymsg '[app_id="org.telegram.desktop"] move left, splith, mark app' && \
    swaymsg '[app_id="chrome-*" title="MAX"] move to mark app, move left, layout tabbed' && \
    swaymsg 'unmark app'
}
