set $gnome-interface org.gnome.desktop.interface
exec {
  gsettings set $gnome-interface monospace-font-name  'Hack 11'
  gsettings set $gnome-interface font-name            'Ubuntu 11'
  gsettings set $gnome-interface color-scheme         'prefer-dark'
  gsettings set $gnome-interface gtk-theme            'Breeze-Dark'
  gsettings set $gnome-interface icon-theme           'breeze-dark'
}

assign [app_id="org.telegram.desktop"] 3
assign [app_id="chrome-*" title="MAX"] 3
assign [app_id="chrome-*" title="MAX"] floating disable
assign [app_id="org.mozilla.firefox.webapp-*" title="MAX*"] 3

exec {
  ~/bin/wlsunset.sh start

  org.telegram.desktop
  thunderbird
  sleep 5 && gtk-launch MAX.desktop
}

exec {
  sleep 8 && \
    swaymsg '[app_id="org.telegram.desktop"] move left, splith, mark app' && \
    swaymsg '[app_id="org.mozilla.firefox.webapp-142b90b6-9bb6-4f47-a2d8-200058e77412"] move to mark app, move left, layout tabbed' && \
    swaymsg 'unmark app'
}
