# output eDP-1 mode 2880x1800@120Hz scale 1.65  adaptive_sync on

assign [app_id="org.telegram.desktop"] 3
assign [app_id="chrome-*" title="MAX"] 3
assign [app_id="chrome-*" title="MAX"] floating disable
assign [app_id="org.mozilla.firefox.webapp-*" title="MAX*"] 3

exec {
  swayidle -w \
    timeout 300 'swaymsg "output * power off"' \
      resume 'swaymsg "output * power on"' \
    before-sleep 'loginctl lock-session' \
    lock 'swaylock -f'

  # firewall-applet
  nm-applet

  ~/bin/wlsunset.sh start

  Telegram
  thunderbird
  sleep 5 && gtk-launch MAX.desktop
}

exec {
  sleep 8 && \
    swaymsg '[app_id="org.telegram.desktop"] move left, splith, mark app, resize grow width 50 px' && \
    swaymsg '[app_id="org.mozilla.firefox.webapp-*" title="MAX*"] move to mark app, move left, layout tabbed' && \
    swaymsg 'unmark app'
}
