# --enable-features=VaapiVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE
--extension-mime-request-handling=always-prompt-for-install
--password-store=gnome-libsecret
--disable-features=ExtensionManifestV2Unsupported,ExtensionManifestV2Disabled
--restore-last-session
--enable-usermedia-screen-capturing
