[preferred]
default=wlr,gtk
org.freedesktop.impl.portal.FileChooser=lxqt
org.freedesktop.impl.portal.Secret=oo7-portal

[screencast]
exec_before=makoctl mode -a do-not-disturb
exec_after=makoctl mode -r do-not-disturb
