version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -s -bn'
    format-stdin: true

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

  python-flake8: &python-flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  python-black: &python-black
    format-command: 'black --quiet -'
    format-stdin: true

  python-autopep8: &python-autopep8
    format-command: 'autopep8 -'
    format-stdin: true

languages:
  sh:
    - <<: *sh-shfmt

  yaml:
    - <<: *yaml-yamllint

  python:
    - <<: *python-flake8
    # - <<: *python-black
    - <<: *python-autopep8

