[General]
__userfile__=true

[backlight]
alignment=Right
type=backlight

[customcommand]
alignment=Right
command=~/bin/power_consumption.sh
repeatTimer=2
runWithBash=true
text=%1
tooltip=
type=customcommand

[desktopswitch]
alignment=Left

[fancymenu]
favorites\1\desktopFile=/usr/share/applications/lxqt-lockscreen.desktop
favorites\2\desktopFile=/usr/share/applications/lxqt-suspend.desktop
favorites\3\desktopFile=/usr/share/applications/org.qbittorrent.qBittorrent.desktop
favorites\size=3

[panel1]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
hide-on-overlap=false
iconSize=22
lineCount=1
lockPanel=false
opacity=100
panelSize=24
plugins=fancymenu, desktopswitch, quicklaunch, taskbar, customcommand, statusnotifier, volume, backlight, worldclock
position=Top
reserve-space=true
screen-name=eDP-1
show-delay=0
visible-margin=true
width=100
width-percent=true

[quicklaunch]
apps\1\desktop=/usr/share/applications/pcmanfm-qt.desktop
apps\size=1

[taskbar]
alignment=Left
autoRotate=true
buttonHeight=100
buttonStyle=IconText
buttonWidth=220
closeOnMiddleClick=true
excludedList=
groupingEnabled=false
iconByClass=true
raiseOnCurrentDesktop=false
showDesktopNum=0
showGroupOnHover=true
showOnlyCurrentScreenTasks=false
showOnlyMinimizedTasks=false
showOnlyOneDesktopTasks=true
ungroupedNextToExisting=false
wheelDeltaThreshold=300
wheelEventsAction=0

[volume]
alignment=Right

[worldclock]
alignment=Right
