#!/bin/bash
VALUE=$(cat /proc/net/wireless | tail -n 1 | awk '{print int($3 * 100 / 70)}')

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
	freq=$(iwgetid -f -r | rev | cut -c 5- | rev)
	ssid=$(iwgetid -r)
	ch=$(iwgetid -c -r)

	echo "${ssid} ${freq}GHz ${ch}Ch"
	exit 0
fi

VPN_STATUS=''
if [[ $(ip tuntap show | wc -l) -gt 0 ]]; then
	VPN_STATUS='^VPN '
fi

if [[ ${VALUE} -eq 0 ]]; then
	echo "down"
	echo "down"
	echo ${COLOR_H}

else
	echo "${VALUE}% ${VPN_STATUS}"
	#echo ${VALUE}%
	echo ${VALUE}%

	if [[ ${VALUE} -lt 30 ]]; then
		echo ${COLOR_H}

	elif [[ ${VALUE} -lt 70 ]]; then
		echo ${COLOR_M}
	
	else
		echo ${COLOR_G}

	fi
fi
