#!/bin/bash

gsettings set org.gnome.desktop.interface text-scaling-factor 1.65
gsettings set org.gnome.desktop.interface cursor-size 42

export I3SOCK=$(i3 --get-socketpath)

i3-msg restart
dunstctl reload
