exec {
  /usr/bin/lxqt-policykit-agent
  /usr/lib/geoclue-2.0/demos/agent

  wl-paste --watch cliphist store
  mako
  kanshi
  swayidle -w
  sway-kbdd.py
}

exec_always {
  i3-recent-window.py
  i3-switch-workspace.py
  kanshictl reload
}

exec {
  foot -a foot-tmux -e tmux-workspace.sh
  pcmanfm-qt -d
  blueman-applet
  firefox
  sleep 5 && keepassxc
}
