#!/bin/sh
SYS_PATH='/sys/class/power_supply'
BATT_ID='BAT0'

B_LEVEL=$(cat $SYS_PATH/$BATT_ID/capacity)
B_VOLTAGE=$(cat $SYS_PATH/$BATT_ID/current_now)
B_STATUS=$(cat $SYS_PATH/$BATT_ID/status)

B_VOLTAGE=$(echo "scale=1;$B_VOLTAGE / 100000" | bc -l)

if [[ "${B_STATUS}" -eq 'Discharging' ]]; then
  B_STATUS='DIS'
elif [[ "${B_STATUS}" -eq 'Charging' ]]; then
  B_STATUS='CHR'
fi

echo "${B_LEVEL}% ${B_STATUS} (${B_VOLTAGE}W)"
echo "${B_LEVEL}% ${B_STATUS} (${B_VOLTAGE}W)"


if [[ ${B_LEVEL} -lt 5 ]]; then
	exit 33

elif [[ ${B_LEVEL} -lt 20 ]]; then
	echo "#FF0000"
elif [[ ${B_LEVEL} -lt 40 ]]; then
	echo "#FFAE00"
elif [[ ${B_LEVEL} -lt 60 ]]; then
	echo "#FFF600"
elif [[ ${B_LEVEL} -lt 90 ]]; then
	echo "#A8FF00"
fi

