#!/bin/bash

BR_STEP=2
if [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
  brightnessctl set +${BR_STEP}% >> /dev/null

elif [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
	brightnessctl -n set ${BR_STEP}%- >> /dev/null
fi

VALUE=$(echo "scale=0;$(xbacklight -get)" | bc -l)
VALUE=${VALUE%.*}

echo "${VALUE}%"
echo "${VALUE}%"


if [[ ${VALUE} -lt 2 ]]; then
	exit 33

elif [[ ${VALUE} -gt 75 ]]; then
	echo ${COLOR_H}

elif [[ ${VALUE} -gt 40 ]]; then
	echo ${COLOR_M}

fi
