#!/bin/sh

BR_STEP=2
if [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
  xbacklight -inc $BR_STEP

elif [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
	BR_NEW=$(echo "scale=0;$(xbacklight -get)-$BR_STEP" | bc -l)
	if [[ "${BR_NEW%.*}" -ge 1 ]]; then
		xbacklight -dec $BR_STEP
	fi
fi

BR_CURR=$(echo "scale=0;$(xbacklight -get)" | bc -l)
BR_CURR=${BR_CURR%.*}

echo "${BR_CURR}%"
echo "${BR_CURR}%"
