#!/bin/bash
VALUE=$(cat /proc/net/wireless | tail -n 1 | awk '{print int($3 * 100 / 70)}')

if [[ ${VALUE} -eq 0 ]]; then
	echo "down"
	echo "down"
	echo ${COLOR_H}

else
	SSID=$(iwgetid -r)

	echo ${SSID}
	echo ${SSID}

	if [[ ${VALUE} -lt 30 ]]; then
		echo ${COLOR_H}
	fi
fi
